# Generated by Django 4.2.5 on 2023-09-30 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import venue.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Series slug')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Contact Phone')),
                ('web', models.URLField(blank=True, verbose_name='Website Address')),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=40, verbose_name='Email Address')),
                ('price', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, default=venue.models.random_default_picture, upload_to=venue.models.upload_image_to)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
